name: Sync db-tables.json to BDA-Pricer

on:
  push:
    paths:
      - "db-tables.json"
    branches:
      - main  # Cambia se necessario

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UploadPVTFiles repository
        uses: actions/checkout@v4

      - name: Clone BDA-Pricer repository with authentication
        run: |
          git clone https://daveic:${{ secrets.GH_PAT }}@github.com/daveic/BDA-Pricer.git
          cd BDA-Pricer
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
      - name: Show directory structure after cloning
        run: |
          echo "Repository structure after cloning:"
          tree BDA-Pricer || ls -R BDA-Pricer
          
      - name: Copy updated db-tables.json
        run: |
          cp db-tables.json wwwroot/data/



      - name: Commit and push changes to master
        run: |
          cd BDA-Pricer
          git add wwwroot/data/db-tables.json
          git commit -m "Update db-tables.json from UploadPVTFiles"
          git push origin master
